abstract class AppNumber{
  static const double NUMBER_OF_CHIP_EPOSIDES_PER_ROW = 6;
  static const double AVG_NUMBER_OF_HEIGHT_PER_ROW = 50;

  static const int NUMBER_OF_DURATION_FADE_IN_MILLISECONDS = 2000;
  static const int NUMBER_OF_DURATION_SCROLL_MILLISECONDS = 1000;
  static const int NUMBER_OF_DURATION_OPACITY_BUTTON_ON_PLAY_VIDEO_MILLISECONDS = 300;
  static const int NUMBER_OF_DURATION_COUNTDOWN_HIDE_BUTTON_ON_PLAY_VIDEO_SECONDS = 4;
  static const int NUMBER_OF_DURATION_WAIT_SPLASH_SCREEN_SECONDS = 9;
  static const int NUMBER_OF_DURATION_ANIMATE_GRADIENT_SECONDS = 3;

  static const int TOTAL_YEAR_RENDER_IN_LIST_YEAR = 10;

  static const int DEFAULT_TOTAL_YEAR_RENDER_IN_LIST_YEAR = 10;
  static const int DEFAULT_HEIGHT_OF_FATHER_TABBAR = 80;
  static const int DEFAULT_HEIGHT_OF_CHILD_TABBAR = 30;
  static const int DEFAULT_NUMBER_OF_COLOR = 6;

  static const int COUNT_EPISODE_OF_MOVIE= 1;
}